### ISSUE TITLE
Error when executing "bbb handlebars"

### ISSUE THREAD

**Issue by Golodhros** [raDiesle/backbone.js-jquerymobile-boilerplate-template#9]
Hi there, 

I have follow your installation instructions, but when I get to the handlebars precompilation step I got this error:
    Error: TypeError: Object #<Object> has no method 'options'
        at Object.module.exports (/var/www/sparked/cab-mobile/node_modules/grunt-contrib/node_modules/grunt-contrib-handlebars/tasks/handlebars.js:35:24)
        at Object.task.registerMultiTask.thisTask (/usr/lib/node_modules/bbb/node_modules/grunt/lib/grunt/task.js:109:15)
        at Object.task.registerTask.thisTask.fn (/usr/lib/node_modules/bbb/node_modules/grunt/lib/grunt/task.js:58:16)
        at Task.<anonymous> (/usr/lib/node_modules/bbb/node_modules/grunt/lib/util/task.js:343:36)
        at Task.<anonymous> (/usr/lib/node_modules/bbb/node_modules/grunt/lib/util/task.js:319:9)
        at Task.<anonymous> (/usr/lib/node_modules/bbb/node_modules/grunt/lib/util/task.js:346:11)
        at Task.start (/usr/lib/node_modules/bbb/node_modules/grunt/lib/util/task.js:359:5)
        at Object.grunt.tasks (/usr/lib/node_modules/bbb/node_modules/grunt/lib/grunt.js:143:8)
        at Object.module.exports [as cli](/usr/lib/node_modules/bbb/node_modules/grunt/lib/grunt/cli.js:36:9)
        at Object.<anonymous> (/usr/lib/node_modules/bbb/bbb.js:98:7)

Could it be due to a change in bbb contrib? 

Many thanks for your awesome work!

**Comment by raDiesle** [comment]
Hi Golodhros,

thanks for your information.

I am currently investigating in 
https://github.com/raDiesle/backbone-fundamentals/blob/gh-pages/chapters/10-mobile-applications.md
as well as 
https://github.com/raDiesle/backbone-fundamentals/tree/gh-pages/practicals/todo-jqm-app
which was already merged with the trunk.

Within next week, I'm planning to update to the newest libraries, so stay tuned!

**Comment by Golodhros** [comment]
Thanks!

**Comment by kingnight** [comment]
i find the similar problem , wait for your update

**Comment by raDiesle** [comment]
I commited the upgrade to grunt 0.4.0.
Can you check it again.

The steps needed are :

npm uninstall -g grunt

npm install -g grunt-cli
// actually not needed
npm install grunt --save-dev  

then run :
grunt handlebars
grunt connect:server:keepalive

Is it working for you?

**Comment by Golodhros** [comment]
It's Working!!
Thanks a lot!!

**Comment by kingnight** [comment]
ok,working , thanks a lot ,the chapter - 10-mobile-applications, very helpful to me !

**Comment by johntday** [comment]
Not working.
